# Generated by Django 4.2.3 on 2023-07-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='news_image'),
            preserve_default=False,
        ),
    ]
